Vagrant::Config.run do |config|
  config.vm.host_name = "disco1.x"
  config.vm.box = "debian-64-stable"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/13054557/vagrant_boxes/debian-squeeze.box"
  config.vm.network :bridged, :mac => '08802711E9AA'  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../"
    chef.add_recipe("disco::master")
  end
end

